settings:
  enable: true
  pre-resolve: false
  display: "cooldown"

attributes:
  attack-interval:
    name: "攻击冷却"
    unit: "tick"
  attack-interval-reduction:
    name: "攻击冷却缩减"
    unit: "%"
  attack-distance:
    name: "攻击距离"
    unit: "block"

message:
